apiVersion: hypershift.openshift.io/v1alpha1
kind: HostedCluster
metadata:
  name: 'cust-01'
  namespace: 'cust-01'
  labels:
spec:
  release:
    image: quay.io/openshift-release-dev/ocp-release:4.13.5-x86_64
  pullSecret:
    name: cluster-cust-01-pullsecret
  sshKey:
    name: cluster-cust-01-sshkey
  networking:
    podCIDR: 10.132.0.0/14
    serviceCIDR: 172.31.0.0/16
    machineCIDR: 10.6.82.0/24
  platform:
    type: Agent
    agent:
      agentNamespace: 'baremetal'
  infraID: 'cust-01'
  dns:
    baseDomain: 'hcp.numspot.cloud'
  services:
  - service: APIServer
    servicePublishingStrategy:
      type: NodePort
      nodePort:
        address: 10.6.82.55
        port: 0
  - service: OAuthServer
    servicePublishingStrategy:
      type: Route
  - service: OIDC
    servicePublishingStrategy:
      type: Route
  - service: Konnectivity
    servicePublishingStrategy:
      type: Route
  - service: Ignition
    servicePublishingStrategy:
      type: Route
